import { LANGUAGE_NAMES } from 'langs/languageNames';

export const ar: Record<string, string> = {
  'tabs.search': 'بحث',
  'tabs.threads': 'سلاسل',
  'tabs.settings': 'الإعدادات',
  'nav.back': 'رجوع',
  'nav.thread': 'سلسلة',
  'nav.messages': 'الرسائل',
  'nav.threadsBack': 'سلاسل',
  'onboarding.slide0.title': 'ويب بلا ضجيج',
  'onboarding.slide0.body':
    'محتوى بلا إعلانات أو متعقّبات أو سكربتات غير ضرورية. فقط نص وبنية تخصّك وتعمل بسرعة على أي جهاز.',
  'onboarding.slide1.title': 'تصفّح كسلاسل',
  'onboarding.slide1.body':
    'كل زيارة تصبح سلسلة قابلة للقراءة — تسلسل صفحات فتحتها. كأنها محادثة مع الويب حيث يُحفظ السياق وتبدو الملاحة طبيعية.',
  'onboarding.slide2.title': 'دائمًا معك',
  'onboarding.slide2.body':
    'المواقع التي تزورها تُحفظ كسلاسل على جهازك، ومتاحة دون اتصال مع سجل تصفّح كامل — جاهزة للعودة إليها في أي وقت.',
  'onboarding.back': 'رجوع',
  'onboarding.next': 'التالي',
  'onboarding.getStarted': 'ابدأ',
  'onboarding.a11y.back': 'رجوع',
  'onboarding.a11y.next': 'التالي',
  'onboarding.a11y.getStarted': 'ابدأ',
  'threads.header.addA11y': 'إضافة',
  'threads.toast.saved.title': 'تم الحفظ',
  'threads.toast.saved.message': 'تم تسجيل التغيير.',
  'threadList.empty': 'لا توجد سلاسل بعد.',
  'messageList.empty': 'لا توجد رسائل في هذه السلسلة.',
  'search.title': 'بحث',
  'search.subtitle': 'ابحث في الحوارات أو المستخدمين أو أي شيء آخر.',
  'settings.language': 'اللغة',
  'settings.account': 'الحساب',
  'settings.languagePicker.title': 'اللغة',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'إغلاق',
  'a11y.dismiss': 'إغلاق',
  'accountSelector.title': 'الحسابات',
  'accountSelector.addNew': 'إضافة حساب جديد',
  'accountSelector.empty': 'لا توجد حسابات بعد.',
  'accountForm.title': 'حساب جديد',
  'accountForm.save': 'حفظ',
  'accountForm.nameLabel': 'الاسم',
  'accountForm.namePlaceholder': 'اسم الحساب',
  'accountForm.avatarHint': 'اسحب لاختيار إيموجي',
  'account.toast.savedTitle': 'تم حفظ الحساب',
  'account.validation.nameRequired': 'الاسم مطلوب',
  'account.validation.nameTooLong': 'الاسم طويل جدًا',
  'demo.thread.1.title': 'مزامنة التصميم',
  'demo.thread.1.desc': 'مناقشة أنماط التنقّل لـ v2.',
  'demo.thread.2.title': 'إصدار الجوال',
  'demo.thread.3.title': 'صندوق دعم الوارد',
  'demo.thread.3.desc': 'تذاكر نهاية الأسبوع في قائمة الانتظار.',
  'demo.thread.4.title': 'سلسلة بسيطة A',
  'demo.thread.4.desc': 'بدون صورة أو إيموجي أو لون للأفاتار — الأحرف الأولى فقط.',
  'demo.thread.5.title': 'ملاحظات الوقوف الأسبوعية',
  'demo.thread.5.desc': 'عنوان من كلمتين للأحرف الأولى.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'حالة حافة: عنوان بحرف واحد.',
  'demo.thread.fallback.title': 'سلسلة',
  'demo.thread.fallback.desc': 'عنوان مثال عندما يكون معرّف السلسلة غير معروف.',
  'demo.message.1.label': 'لخّص هذه السلسلة',
  'demo.message.1.body':
    'إليك **ملخصًا قصيرًا** للنقاش:\n\n- التنقّل\n- القوائم\n- الحالات الفارغة',
  'demo.message.2.input': 'ما تاريخ الإصدار؟',
  'demo.message.3.label': 'مسودة رد',
  'demo.message.3.body': 'نستهدف **الجمعة القادمة** لبناء الجوال.',
  'demo.message.4.input': 'تشغيل فحص الالتزام',
  'demo.message.4.error': 'انتهت مهلة خدمة الالتزام. حاول مرة أخرى.',
};

