import { LANGUAGE_NAMES } from 'langs/languageNames';

export const de: Record<string, string> = {
  'tabs.search': 'Suche',
  'tabs.threads': 'Threads',
  'tabs.settings': 'Einstellungen',
  'nav.back': 'Zurück',
  'nav.thread': 'Thread',
  'nav.messages': 'Nachrichten',
  'nav.threadsBack': 'Threads',
  'onboarding.slide0.title': 'Ein Web ohne Lärm',
  'onboarding.slide0.body':
    'Inhalte ohne Werbung, Tracker oder unnötige Skripte. Nur Text und Struktur, die Ihnen gehören und auf jedem Gerät schnell laufen.',
  'onboarding.slide1.title': 'Im Thread lesen',
  'onboarding.slide1.body':
    'Jeder Besuch wird zu einem lesbaren Thread — einer Sequenz der Seiten, die Sie geöffnet haben. Wie ein Gespräch mit dem Web: Kontext bleibt erhalten und die Navigation fühlt sich natürlich an.',
  'onboarding.slide2.title': 'Immer dabei',
  'onboarding.slide2.body':
    'Besuchte Seiten werden als Threads auf Ihrem Gerät gespeichert, offline mit vollständiger Verlaufshistorie — jederzeit wieder abrufbar.',
  'onboarding.back': 'Zurück',
  'onboarding.next': 'Weiter',
  'onboarding.getStarted': 'Loslegen',
  'onboarding.a11y.back': 'Zurück',
  'onboarding.a11y.next': 'Weiter',
  'onboarding.a11y.getStarted': 'Loslegen',
  'threads.header.addA11y': 'Hinzufügen',
  'threads.toast.saved.title': 'Gespeichert',
  'threads.toast.saved.message': 'Ihre Änderung wurde übernommen.',
  'threadList.empty': 'Noch keine Threads.',
  'messageList.empty': 'Keine Nachrichten in diesem Thread.',
  'search.title': 'Suche',
  'search.subtitle': 'Dialoge, Nutzer:innen oder beliebige Inhalte durchsuchen.',
  'settings.language': 'Sprache',
  'settings.account': 'Konto',
  'settings.languagePicker.title': 'Sprache',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Schließen',
  'a11y.dismiss': 'Schließen',
  'accountSelector.title': 'Konten',
  'accountSelector.addNew': 'Neues Konto',
  'accountSelector.empty': 'Noch keine Konten.',
  'accountForm.title': 'Neues Konto',
  'accountForm.save': 'Speichern',
  'accountForm.nameLabel': 'Name',
  'accountForm.namePlaceholder': 'Kontoname',
  'accountForm.avatarHint': 'Wischen, um ein Emoji zu wählen',
  'account.toast.savedTitle': 'Konto gespeichert',
  'account.validation.nameRequired': 'Name ist erforderlich',
  'account.validation.nameTooLong': 'Name ist zu lang',
  'demo.thread.1.title': 'Design-Abstimmung',
  'demo.thread.1.desc': 'Navigationsmuster für v2 besprechen.',
  'demo.thread.2.title': 'Mobile Release',
  'demo.thread.3.title': 'Support-Posteingang',
  'demo.thread.3.desc': 'Tickets vom Wochenende in der Warteschlange.',
  'demo.thread.4.title': 'Einfacher Thread A',
  'demo.thread.4.desc': 'Kein Bild, Emoji oder Avatarfarbe — nur Initialen.',
  'demo.thread.5.title': 'Wöchentliche Stand-up-Notizen',
  'demo.thread.5.desc': 'Zweiworttitel für Initialen.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Randfall: Titel mit einem Buchstaben.',
  'demo.thread.fallback.title': 'Thread',
  'demo.thread.fallback.desc': 'Beispielkopfzeile, wenn die Thread-ID unbekannt ist.',
  'demo.message.1.label': 'Diesen Thread zusammenfassen',
  'demo.message.1.body':
    'Hier ist eine **kurze Zusammenfassung** der Diskussion:\n\n- Navigation\n- Listen\n- Leere Zustände',
  'demo.message.2.input': 'Wann ist der Release-Termin?',
  'demo.message.3.label': 'Antwortentwurf',
  'demo.message.3.body': 'Wir planen **nächsten Freitag** für den Mobile-Build.',
  'demo.message.4.input': 'Compliance-Prüfung ausführen',
  'demo.message.4.error': 'Der Compliance-Dienst hat nicht rechtzeitig geantwortet. Bitte erneut versuchen.',

  'supportUkraine.banner.title': 'Unterstützen Sie die Ukraine',
  'supportUkraine.banner.body':
    'Tippen Sie, um UNITED24 zu öffnen und humanitäre Hilfe zu unterstützen.',
};

