import { LANGUAGE_NAMES } from 'langs/languageNames';

export const en: Record<string, string> = {
  'tabs.search': 'Search',
  'tabs.threads': 'Threads',
  'tabs.settings': 'Settings',
  'nav.back': 'Back',
  'nav.thread': 'Thread',
  'nav.messages': 'Messages',
  'nav.threadsBack': 'Threads',
  'onboarding.slide0.title': 'A web without noise',
  'onboarding.slide0.body':
    'Content without ads, trackers, or unnecessary scripts. Just text and structure that belong to you and work fast on any device.',
  'onboarding.slide1.title': 'Browse in threads',
  'onboarding.slide1.body':
    'Every visit becomes a readable thread — a sequence of pages you opened. Like a conversation with the web, where context is preserved and navigation feels natural.',
  'onboarding.slide2.title': 'Always with you',
  'onboarding.slide2.body':
    'Sites you visit are saved as threads on your device, available offline with full browsing history — ready to revisit anytime.',
  'onboarding.back': 'Back',
  'onboarding.next': 'Next',
  'onboarding.getStarted': 'Get started',
  'onboarding.a11y.back': 'Back',
  'onboarding.a11y.next': 'Next',
  'onboarding.a11y.getStarted': 'Get started',
  'threads.header.addA11y': 'Add',
  'threads.toast.saved.title': 'Saved',
  'threads.toast.saved.message': 'Your change was recorded.',
  'threadList.empty': 'No threads yet.',
  'messageList.empty': 'No messages in this thread.',
  'search.title': 'Search',
  'search.subtitle': 'Search dialogs, users, or anything else.',
  'settings.language': 'Language',
  'settings.account': 'Account',
  'settings.languagePicker.title': 'Language',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Close',
  'a11y.dismiss': 'Dismiss',
  'accountSelector.title': 'Accounts',
  'accountSelector.addNew': 'Add new account',
  'accountSelector.empty': 'No accounts yet.',
  'accountForm.title': 'New account',
  'accountForm.save': 'Save',
  'accountForm.nameLabel': 'Name',
  'accountForm.namePlaceholder': 'Account name',
  'accountForm.avatarHint': 'Swipe to choose emoji',
  'account.toast.savedTitle': 'Account saved',
  'account.validation.nameRequired': 'Name is required',
  'account.validation.nameTooLong': 'Name is too long',
  'demo.thread.1.title': 'Design sync',
  'demo.thread.1.desc': 'Discuss navigation patterns for v2.',
  'demo.thread.2.title': 'Mobile release',
  'demo.thread.3.title': 'Support inbox',
  'demo.thread.3.desc': 'Queued tickets from the weekend.',
  'demo.thread.4.title': 'Plain thread A',
  'demo.thread.4.desc': 'No image, emoji, or avatar tint — initials only.',
  'demo.thread.5.title': 'Weekly standup notes',
  'demo.thread.5.desc': 'Two-word title for initials.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Single-letter title edge case.',
  'demo.thread.fallback.title': 'Thread',
  'demo.thread.fallback.desc': 'Example header when thread id is unknown.',
  'demo.message.1.label': 'Summarize this thread',
  'demo.message.1.body':
    'Here is a **short summary** of the discussion:\n\n- Navigation\n- Lists\n- Empty states',
  'demo.message.2.input': 'What is the release date?',
  'demo.message.3.label': 'Draft reply',
  'demo.message.3.body': 'We are targeting **next Friday** for the mobile build.',
  'demo.message.4.input': 'Run compliance check',
  'demo.message.4.error': 'The compliance service timed out. Please try again.',

  'supportUkraine.banner.title': 'Support Ukraine',
  'supportUkraine.banner.body': 'Tap to visit UNITED24 and support humanitarian relief.',
};

