import { LANGUAGE_NAMES } from 'langs/languageNames';

export const es: Record<string, string> = {
  'tabs.search': 'Buscar',
  'tabs.threads': 'Hilos',
  'tabs.settings': 'Ajustes',
  'nav.back': 'Atrás',
  'nav.thread': 'Hilo',
  'nav.messages': 'Mensajes',
  'nav.threadsBack': 'Hilos',
  'onboarding.slide0.title': 'Una web sin ruido',
  'onboarding.slide0.body':
    'Contenido sin anuncios, rastreadores ni scripts innecesarios. Solo texto y estructura que son tuyos y van rápido en cualquier dispositivo.',
  'onboarding.slide1.title': 'Navega en hilos',
  'onboarding.slide1.body':
    'Cada visita se convierte en un hilo legible: una secuencia de páginas que abriste. Como una conversación con la web, donde se conserva el contexto y la navegación resulta natural.',
  'onboarding.slide2.title': 'Siempre contigo',
  'onboarding.slide2.body':
    'Los sitios que visitas se guardan como hilos en tu dispositivo, disponibles sin conexión con el historial completo, listos para volver cuando quieras.',
  'onboarding.back': 'Atrás',
  'onboarding.next': 'Siguiente',
  'onboarding.getStarted': 'Empezar',
  'onboarding.a11y.back': 'Atrás',
  'onboarding.a11y.next': 'Siguiente',
  'onboarding.a11y.getStarted': 'Empezar',
  'threads.header.addA11y': 'Añadir',
  'threads.toast.saved.title': 'Guardado',
  'threads.toast.saved.message': 'Se ha registrado tu cambio.',
  'threadList.empty': 'Aún no hay hilos.',
  'messageList.empty': 'No hay mensajes en este hilo.',
  'messageList.startPress': 'Iniciar',
  'messageForm.startPress': 'Iniciar',
  'messageForm.replyPlaceholder': 'Mensaje',
  'a11y.menu': 'Menú',
  'a11y.sendMessage': 'Enviar',
  'search.title': 'Buscar',
  'search.subtitle': 'Busca diálogos, usuarios o cualquier otra cosa.',
  'settings.language': 'Idioma',
  'settings.account': 'Cuenta',
  'settings.languagePicker.title': 'Idioma',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Cerrar',
  'a11y.dismiss': 'Cerrar',
  'accountSelector.title': 'Cuentas',
  'accountSelector.addNew': 'Añadir cuenta',
  'accountSelector.empty': 'Aún no hay cuentas.',
  'accountForm.title': 'Cuenta nueva',
  'accountForm.save': 'Guardar',
  'accountForm.nameLabel': 'Nombre',
  'accountForm.namePlaceholder': 'Nombre de la cuenta',
  'accountForm.avatarHint': 'Desliza para elegir un emoji',
  'account.toast.savedTitle': 'Cuenta guardada',
  'account.validation.nameRequired': 'El nombre es obligatorio',
  'account.validation.nameTooLong': 'El nombre es demasiado largo',
  'demo.thread.1.title': 'Sincro de diseño',
  'demo.thread.1.desc': 'Patrones de navegación para la v2.',
  'demo.thread.2.title': 'Lanzamiento móvil',
  'demo.thread.3.title': 'Bandeja de soporte',
  'demo.thread.3.desc': 'Tickets en cola del fin de semana.',
  'demo.thread.4.title': 'Hilo simple A',
  'demo.thread.4.desc': 'Sin imagen, emoji ni tinte del avatar: solo iniciales.',
  'demo.thread.5.title': 'Notas del standup semanal',
  'demo.thread.5.desc': 'Título de dos palabras para iniciales.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Caso límite: título de una sola letra.',
  'demo.thread.fallback.title': 'Hilo',
  'demo.thread.fallback.desc': 'Cabecera de ejemplo cuando el id del hilo es desconocido.',
  'demo.message.1.label': 'Resume este hilo',
  'demo.message.1.body':
    'Aquí tienes un **resumen breve** del debate:\n\n- Navegación\n- Listas\n- Estados vacíos',
  'demo.message.2.input': '¿Cuál es la fecha de lanzamiento?',
  'demo.message.3.label': 'Borrador de respuesta',
  'demo.message.3.body': 'Apuntamos a **el próximo viernes** para la build móvil.',
  'demo.message.4.input': 'Ejecutar comprobación de cumplimiento',
  'demo.message.4.error': 'El servicio de cumplimiento tardó demasiado. Inténtalo de nuevo.',

  'supportUkraine.banner.title': 'Apoya a Ucrania',
  'supportUkraine.banner.body':
    'Toca para visitar UNITED24 y apoyar la ayuda humanitaria.',
};

