import { LANGUAGE_NAMES } from 'langs/languageNames';

export const fa: Record<string, string> = {
  'tabs.search': 'جستجو',
  'tabs.threads': 'رشته‌ها',
  'tabs.settings': 'تنظیمات',
  'nav.back': 'بازگشت',
  'nav.thread': 'رشته',
  'nav.messages': 'پیام‌ها',
  'nav.threadsBack': 'رشته‌ها',
  'onboarding.slide0.title': 'وبِ بدون شلوغی',
  'onboarding.slide0.body':
    'محتوا بدون تبلیغات، ردیاب‌ها یا اسکریپت‌های غیرضروری. فقط متن و ساختاری که متعلق به شماست و روی هر دستگاهی سریع کار می‌کند.',
  'onboarding.slide1.title': 'مرور به شکل رشته',
  'onboarding.slide1.body':
    'هر بازدید به یک رشته‌ی خوانا تبدیل می‌شود — دنباله‌ای از صفحاتی که باز کرده‌اید. مثل یک گفت‌وگو با وب: زمینه حفظ می‌شود و ناوبری طبیعی به نظر می‌رسد.',
  'onboarding.slide2.title': 'همیشه همراه شما',
  'onboarding.slide2.body':
    'سایت‌هایی که می‌بینید به‌صورت رشته روی دستگاه ذخیره می‌شوند، آفلاین با تاریخچه‌ی کامل — آماده برای بازگشت در هر زمان.',
  'onboarding.back': 'بازگشت',
  'onboarding.next': 'بعدی',
  'onboarding.getStarted': 'شروع',
  'onboarding.a11y.back': 'بازگشت',
  'onboarding.a11y.next': 'بعدی',
  'onboarding.a11y.getStarted': 'شروع',
  'threads.header.addA11y': 'افزودن',
  'threads.toast.saved.title': 'ذخیره شد',
  'threads.toast.saved.message': 'تغییر شما ثبت شد.',
  'threadList.empty': 'هنوز رشته‌ای نیست.',
  'messageList.empty': 'در این رشته پیامی وجود ندارد.',
  'messageList.startPress': 'شروع',
  'messageForm.startPress': 'شروع',
  'messageForm.replyTextPlaceholder': 'پاسخ بنویسید',
  'a11y.menu': 'منو',
  'a11y.sendMessage': 'ارسال',
  'search.title': 'جستجو',
  'search.subtitle': 'گفت‌وگوها، کاربران یا هر چیز دیگری را جستجو کنید.',
  'settings.language': 'زبان',
  'settings.account': 'حساب',
  'settings.languagePicker.title': 'زبان',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'بستن',
  'a11y.dismiss': 'بستن',
  'accountSelector.title': 'حساب‌ها',
  'accountSelector.addNew': 'افزودن حساب جدید',
  'accountSelector.empty': 'هنوز حسابی نیست.',
  'accountForm.title': 'حساب جدید',
  'accountForm.save': 'ذخیره',
  'accountForm.nameLabel': 'نام',
  'accountForm.namePlaceholder': 'نام حساب',
  'accountForm.avatarHint': 'برای انتخاب ایموجی بکشید',
  'account.toast.savedTitle': 'حساب ذخیره شد',
  'account.validation.nameRequired': 'نام الزامی است',
  'account.validation.nameTooLong': 'نام خیلی طولانی است',
  'demo.thread.1.title': 'همگام‌سازی طراحی',
  'demo.thread.1.desc': 'الگوهای ناوبری برای v2 را بررسی کنید.',
  'demo.thread.2.title': 'انتشار موبایل',
  'demo.thread.3.title': 'صندوق پشتیبانی',
  'demo.thread.3.desc': 'تیکت‌های آخر هفته در صف.',
  'demo.thread.4.title': 'رشته‌ی ساده A',
  'demo.thread.4.desc': 'بدون تصویر، ایموجی یا رنگ آواتار — فقط حروف اول.',
  'demo.thread.5.title': 'یادداشت‌های استندآپ هفتگی',
  'demo.thread.5.desc': 'عنوان دوکلمه‌ای برای حروف اول.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'حالت مرزی: عنوان یک‌حرفی.',
  'demo.thread.fallback.title': 'رشته',
  'demo.thread.fallback.desc': 'سربرگ نمونه وقتی شناسه‌ی رشته ناشناخته است.',
  'demo.message.1.label': 'این رشته را خلاصه کن',
  'demo.message.1.body':
    'این هم یک **خلاصه‌ی کوتاه** از گفت‌وگو:\n\n- ناوبری\n- فهرست‌ها\n- حالت‌های خالی',
  'demo.message.2.input': 'تاریخ انتشار چیست؟',
  'demo.message.3.label': 'پیش‌نویس پاسخ',
  'demo.message.3.body': 'برای بیلد موبایل **جمعه‌ی آینده** را هدف گرفته‌ایم.',
  'demo.message.4.input': 'اجرای بررسی انطباق',
  'demo.message.4.error': 'سرویس انطباق زمان‌بر شد. دوباره تلاش کنید.',

  'supportUkraine.banner.title': 'از اوکراین حمایت کنید',
  'supportUkraine.banner.body':
    'برای باز کردن UNITED24 و حمایت از کمک‌های بشردوستانه ضربه بزنید.',
};

