import { LANGUAGE_NAMES } from 'langs/languageNames';

export const fr: Record<string, string> = {
  'tabs.search': 'Recherche',
  'tabs.threads': 'Fils',
  'tabs.settings': 'Réglages',
  'nav.back': 'Retour',
  'nav.thread': 'Fil',
  'nav.messages': 'Messages',
  'nav.threadsBack': 'Fils',
  'onboarding.slide0.title': 'Un web sans bruit',
  'onboarding.slide0.body':
    'Du contenu sans pubs, traqueurs ni scripts inutiles. Juste du texte et une structure qui vous appartiennent et restent rapides sur tout appareil.',
  'onboarding.slide1.title': 'Parcourir en fils',
  'onboarding.slide1.body':
    'Chaque visite devient un fil lisible — une suite de pages que vous avez ouvertes. Comme une conversation avec le web, où le contexte est conservé et la navigation paraît naturelle.',
  'onboarding.slide2.title': 'Toujours avec vous',
  'onboarding.slide2.body':
    'Les sites visités sont enregistrés comme fils sur votre appareil, disponibles hors ligne avec tout l’historique — prêts à être revisités à tout moment.',
  'onboarding.back': 'Retour',
  'onboarding.next': 'Suivant',
  'onboarding.getStarted': 'Commencer',
  'onboarding.a11y.back': 'Retour',
  'onboarding.a11y.next': 'Suivant',
  'onboarding.a11y.getStarted': 'Commencer',
  'threads.header.addA11y': 'Ajouter',
  'threads.toast.saved.title': 'Enregistré',
  'threads.toast.saved.message': 'Votre modification a été enregistrée.',
  'threadList.empty': 'Pas encore de fils.',
  'messageList.empty': 'Aucun message dans ce fil.',
  'messageList.startPress': 'Démarrer',
  'messageForm.startPress': 'Démarrer',
  'search.title': 'Recherche',
  'search.subtitle': 'Recherchez des dialogues, des utilisateurs ou autre chose.',
  'settings.language': 'Langue',
  'settings.account': 'Compte',
  'settings.languagePicker.title': 'Langue',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Fermer',
  'a11y.dismiss': 'Fermer',
  'accountSelector.title': 'Comptes',
  'accountSelector.addNew': 'Ajouter un compte',
  'accountSelector.empty': 'Pas encore de comptes.',
  'accountForm.title': 'Nouveau compte',
  'accountForm.save': 'Enregistrer',
  'accountForm.nameLabel': 'Nom',
  'accountForm.namePlaceholder': 'Nom du compte',
  'accountForm.avatarHint': 'Glissez pour choisir un emoji',
  'account.toast.savedTitle': 'Compte enregistré',
  'account.validation.nameRequired': 'Le nom est obligatoire',
  'account.validation.nameTooLong': 'Le nom est trop long',
  'demo.thread.1.title': 'Point design',
  'demo.thread.1.desc': 'Schémas de navigation pour la v2.',
  'demo.thread.2.title': 'Sortie mobile',
  'demo.thread.3.title': 'Boîte support',
  'demo.thread.3.desc': 'Tickets du week-end en file.',
  'demo.thread.4.title': 'Fil simple A',
  'demo.thread.4.desc': 'Pas d’image, emoji ou teinte d’avatar — initiales seulement.',
  'demo.thread.5.title': 'Notes du stand-up hebdo',
  'demo.thread.5.desc': 'Titre de deux mots pour les initiales.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Cas limite : titre d’une seule lettre.',
  'demo.thread.fallback.title': 'Fil',
  'demo.thread.fallback.desc': 'En-tête d’exemple quand l’id du fil est inconnu.',
  'demo.message.1.label': 'Résume ce fil',
  'demo.message.1.body':
    'Voici un **bref résumé** de la discussion :\n\n- Navigation\n- Listes\n- États vides',
  'demo.message.2.input': 'Quelle est la date de sortie ?',
  'demo.message.3.label': 'Brouillon de réponse',
  'demo.message.3.body': 'Nous visons **vendredi prochain** pour la build mobile.',
  'demo.message.4.input': 'Lancer le contrôle de conformité',
  'demo.message.4.error': 'Le service de conformité a expiré. Réessayez.',

  'supportUkraine.banner.title': 'Soutenez l’Ukraine',
  'supportUkraine.banner.body':
    'Appuyez pour ouvrir UNITED24 et soutenir l’aide humanitaire.',
};

