import { LANGUAGE_NAMES } from 'langs/languageNames';

export const it: Record<string, string> = {
  'tabs.search': 'Cerca',
  'tabs.threads': 'Thread',
  'tabs.settings': 'Impostazioni',
  'nav.back': 'Indietro',
  'nav.thread': 'Thread',
  'nav.messages': 'Messaggi',
  'nav.threadsBack': 'Thread',
  'onboarding.slide0.title': 'Un web senza rumore',
  'onboarding.slide0.body':
    'Contenuti senza annunci, tracker o script superflui. Solo testo e struttura che ti appartengono e sono veloci su qualsiasi dispositivo.',
  'onboarding.slide1.title': 'Naviga in thread',
  'onboarding.slide1.body':
    'Ogni visita diventa un thread leggibile — una sequenza di pagine che hai aperto. Come una conversazione con il web, dove il contesto resta e la navigazione è naturale.',
  'onboarding.slide2.title': 'Sempre con te',
  'onboarding.slide2.body':
    'I siti che visiti si salvano come thread sul dispositivo, disponibili offline con tutta la cronologia — pronti da riaprire in qualsiasi momento.',
  'onboarding.back': 'Indietro',
  'onboarding.next': 'Avanti',
  'onboarding.getStarted': 'Inizia',
  'onboarding.a11y.back': 'Indietro',
  'onboarding.a11y.next': 'Avanti',
  'onboarding.a11y.getStarted': 'Inizia',
  'threads.header.addA11y': 'Aggiungi',
  'threads.toast.saved.title': 'Salvato',
  'threads.toast.saved.message': 'La modifica è stata registrata.',
  'threadList.empty': 'Ancora nessun thread.',
  'messageList.empty': 'Nessun messaggio in questo thread.',
  'messageList.startPress': 'Avvia',
  'messageForm.startPress': 'Avvia',
  'messageForm.replyTextPlaceholder': 'Scrivi una risposta',
  'a11y.menu': 'Menu',
  'a11y.sendMessage': 'Invia',
  'search.title': 'Cerca',
  'search.subtitle': 'Cerca dialoghi, utenti o qualsiasi altra cosa.',
  'settings.language': 'Lingua',
  'settings.account': 'Account',
  'settings.languagePicker.title': 'Lingua',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Chiudi',
  'a11y.dismiss': 'Chiudi',
  'accountSelector.title': 'Account',
  'accountSelector.addNew': 'Aggiungi account',
  'accountSelector.empty': 'Ancora nessun account.',
  'accountForm.title': 'Nuovo account',
  'accountForm.save': 'Salva',
  'accountForm.nameLabel': 'Nome',
  'accountForm.namePlaceholder': 'Nome account',
  'accountForm.avatarHint': 'Scorri per scegliere un emoji',
  'account.toast.savedTitle': 'Account salvato',
  'account.validation.nameRequired': 'Il nome è obbligatorio',
  'account.validation.nameTooLong': 'Il nome è troppo lungo',
  'demo.thread.1.title': 'Allineamento design',
  'demo.thread.1.desc': 'Pattern di navigazione per la v2.',
  'demo.thread.2.title': 'Release mobile',
  'demo.thread.3.title': 'Posta assistenza',
  'demo.thread.3.desc': 'Ticket in coda dal weekend.',
  'demo.thread.4.title': 'Thread semplice A',
  'demo.thread.4.desc': 'Nessuna immagine, emoji o tinta avatar — solo iniziali.',
  'demo.thread.5.title': 'Note standup settimanale',
  'demo.thread.5.desc': 'Titolo di due parole per le iniziali.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Caso limite: titolo di una lettera.',
  'demo.thread.fallback.title': 'Thread',
  'demo.thread.fallback.desc': 'Intestazione di esempio quando l’id del thread è sconosciuto.',
  'demo.message.1.label': 'Riassumi questo thread',
  'demo.message.1.body':
    'Ecco un **breve riassunto** della discussione:\n\n- Navigazione\n- Liste\n- Stati vuoti',
  'demo.message.2.input': 'Qual è la data di release?',
  'demo.message.3.label': 'Bozza di risposta',
  'demo.message.3.body': 'Puntiamo a **venerdì prossimo** per la build mobile.',
  'demo.message.4.input': 'Esegui controllo conformità',
  'demo.message.4.error': 'Il servizio di conformità non ha risposto in tempo. Riprova.',

  'supportUkraine.banner.title': 'Sostieni l’Ucraina',
  'supportUkraine.banner.body':
    'Tocca per aprire UNITED24 e sostenere l’assistenza umanitaria.',
};

