import { LANGUAGE_NAMES } from 'langs/languageNames';

export const kk: Record<string, string> = {
  'tabs.search': 'Іздеу',
  'tabs.threads': 'Тредтер',
  'tabs.settings': 'Баптаулар',
  'nav.back': 'Артқа',
  'nav.thread': 'Тред',
  'nav.messages': 'Хабарламалар',
  'nav.threadsBack': 'Тредтер',
  'onboarding.slide0.title': 'Шусыз веб',
  'onboarding.slide0.body':
    'Жарнамасыз, трекерсіз және қажетсіз скрипттерсіз контент. Тек өзіңізге тиесілі мәтін мен құрылым — кез келген құрылғыда жылдам.',
  'onboarding.slide1.title': 'Тредтермен шолу',
  'onboarding.slide1.body':
    'Әрбір кіру оқуға ыңғайлы тредке айналады — ашқан беттеріңіздің тізбегі. Вебпен әңгіме сияқты: контекст сақталады, навигация табиғи сезіледі.',
  'onboarding.slide2.title': 'Әрқашан қасыңызда',
  'onboarding.slide2.body':
    'Сіз кірген сайттар құрылғыңызда тред ретінде сақталады, офлайн да толық тарихымен — кез келген уақытта қайта қарауға дайын.',
  'onboarding.back': 'Артқа',
  'onboarding.next': 'Келесі',
  'onboarding.getStarted': 'Бастау',
  'onboarding.a11y.back': 'Артқа',
  'onboarding.a11y.next': 'Келесі',
  'onboarding.a11y.getStarted': 'Бастау',
  'threads.header.addA11y': 'Қосу',
  'threads.toast.saved.title': 'Сақталды',
  'threads.toast.saved.message': 'Өзгеріс жазылды.',
  'threadList.empty': 'Әзірге тред жоқ.',
  'messageList.empty': 'Бұл тредте хабарламалар жоқ.',
  'search.title': 'Іздеу',
  'search.subtitle': 'Диалогтарды, пайдаланушыларды немесе басқа нәрсені іздеңіз.',
  'settings.language': 'Тіл',
  'settings.account': 'Есептік жазба',
  'settings.languagePicker.title': 'Тіл',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Жабу',
  'a11y.dismiss': 'Жабу',
  'accountSelector.title': 'Есептік жазбалар',
  'accountSelector.addNew': 'Жаңа есептік жазба қосу',
  'accountSelector.empty': 'Әзірге есептік жазбалар жоқ.',
  'accountForm.title': 'Жаңа есептік жазба',
  'accountForm.save': 'Сақтау',
  'accountForm.nameLabel': 'Аты',
  'accountForm.namePlaceholder': 'Есептік жазба атауы',
  'accountForm.avatarHint': 'Эмодзи таңдау үшін сырғытыңыз',
  'account.toast.savedTitle': 'Есептік жазба сақталды',
  'account.validation.nameRequired': 'Аты міндетті',
  'account.validation.nameTooLong': 'Аты тым ұзын',
  'demo.thread.1.title': 'Дизайн синкі',
  'demo.thread.1.desc': 'v2 үшін навигация үлгілерін талқылау.',
  'demo.thread.2.title': 'Мобильді релиз',
  'demo.thread.3.title': 'Қолдау кірісі',
  'demo.thread.3.desc': 'Демалыстан қалған өтінімдер кезекте.',
  'demo.thread.4.title': 'Қарапайым тред A',
  'demo.thread.4.desc': 'Сурет, эмодзи немесе аватар реңкі жоқ — тек инициалдар.',
  'demo.thread.5.title': 'Апталық стендап жазбалары',
  'demo.thread.5.desc': 'Инициалдарға екі сөздік атау.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Шеткі жағдай: бір әріптік атау.',
  'demo.thread.fallback.title': 'Тред',
  'demo.thread.fallback.desc': 'Тред id белгісіз болғанда мысал тақырып.',
  'demo.message.1.label': 'Осы тредті қорытындылаңыз',
  'demo.message.1.body':
    'Талқылаудың **қысқа қорытындысы**:\n\n- Навигация\n- Тізімдер\n- Бос күйлер',
  'demo.message.2.input': 'Релиз күні қашан?',
  'demo.message.3.label': 'Жауап нобайы',
  'demo.message.3.body': 'Мобильді билд үшін **келесі жұманы** көздеп отырмыз.',
  'demo.message.4.input': 'Сәйкестік тексерісін іске қосу',
  'demo.message.4.error': 'Сәйкестік қызметі уақытында жауап бермеді. Қайта көріңіз.',

  'supportUkraine.banner.title': 'Украинаны қолдаңыз',
  'supportUkraine.banner.body':
    'UNITED24 ашып, гуманитарлық көмекке қолдау көрсету үшін басыңыз.',
};

