import { LANGUAGE_NAMES } from 'langs/languageNames';

export const nl: Record<string, string> = {
  'tabs.search': 'Zoeken',
  'tabs.threads': 'Threads',
  'tabs.settings': 'Instellingen',
  'nav.back': 'Terug',
  'nav.thread': 'Thread',
  'nav.messages': 'Berichten',
  'nav.threadsBack': 'Threads',
  'onboarding.slide0.title': 'Een web zonder ruis',
  'onboarding.slide0.body':
    'Content zonder advertenties, trackers of onnodige scripts. Alleen tekst en structuur die van jou zijn en snel werken op elk apparaat.',
  'onboarding.slide1.title': 'Bladeren in threads',
  'onboarding.slide1.body':
    'Elk bezoek wordt een leesbare thread — een reeks pagina’s die je hebt geopend. Als een gesprek met het web, waarbij context behouden blijft en navigeren natuurlijk aanvoelt.',
  'onboarding.slide2.title': 'Altijd bij je',
  'onboarding.slide2.body':
    'Sites die je bezoekt worden als threads op je apparaat opgeslagen, offline beschikbaar met volledige browsegeschiedenis — klaar om altijd opnieuw te bekijken.',
  'onboarding.back': 'Terug',
  'onboarding.next': 'Volgende',
  'onboarding.getStarted': 'Aan de slag',
  'onboarding.a11y.back': 'Terug',
  'onboarding.a11y.next': 'Volgende',
  'onboarding.a11y.getStarted': 'Aan de slag',
  'threads.header.addA11y': 'Toevoegen',
  'threads.toast.saved.title': 'Opgeslagen',
  'threads.toast.saved.message': 'Je wijziging is opgeslagen.',
  'threadList.empty': 'Nog geen threads.',
  'messageList.empty': 'Geen berichten in deze thread.',
  'messageList.startPress': 'Start',
  'messageForm.startPress': 'Start',
  'search.title': 'Zoeken',
  'search.subtitle': 'Zoek dialogs, gebruikers of iets anders.',
  'settings.language': 'Taal',
  'settings.account': 'Account',
  'settings.languagePicker.title': 'Taal',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Sluiten',
  'a11y.dismiss': 'Sluiten',
  'accountSelector.title': 'Accounts',
  'accountSelector.addNew': 'Nieuw account toevoegen',
  'accountSelector.empty': 'Nog geen accounts.',
  'accountForm.title': 'Nieuw account',
  'accountForm.save': 'Opslaan',
  'accountForm.nameLabel': 'Naam',
  'accountForm.namePlaceholder': 'Accountnaam',
  'accountForm.avatarHint': 'Swipe om emoji te kiezen',
  'account.toast.savedTitle': 'Account opgeslagen',
  'account.add.success.title': 'Account aangemaakt',
  'account.add.success.message': 'Het account is op dit apparaat opgeslagen.',
  'account.add.error.title': 'Account aanmaken mislukt',
  'account.add.error.message': 'Er ging iets mis. Probeer het opnieuw.',
  'account.validation.nameRequired': 'Naam is verplicht',
  'account.validation.nameTooLong': 'Naam is te lang',
  'demo.thread.1.title': 'Design sync',
  'demo.thread.1.desc': 'Bespreek navigatiepatronen voor v2.',
  'demo.thread.2.title': 'Mobiele release',
  'demo.thread.3.title': 'Support-inbox',
  'demo.thread.3.desc': 'Tickets van het weekend in de wachtrij.',
  'demo.thread.4.title': 'Eenvoudige thread A',
  'demo.thread.4.desc': 'Geen afbeelding, emoji of avatartint — alleen initialen.',
  'demo.thread.5.title': 'Wekelijkse stand-up notities',
  'demo.thread.5.desc': 'Titel van twee woorden voor initialen.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Randgeval: titel met één letter.',
  'demo.thread.fallback.title': 'Thread',
  'demo.thread.fallback.desc': 'Voorbeeldkop wanneer thread-id onbekend is.',
  'demo.message.1.label': 'Vat deze thread samen',
  'demo.message.1.body':
    'Hier is een **korte samenvatting** van de discussie:\n\n- Navigatie\n- Lijsten\n- Lege staten',
  'demo.message.2.input': 'Wat is de releasedatum?',
  'demo.message.3.label': 'Conceptantwoord',
  'demo.message.3.body': 'We mikken op **volgende vrijdag** voor de mobiele build.',
  'demo.message.4.input': 'Compliancecheck uitvoeren',
  'demo.message.4.error': 'De compliance-service reageerde niet op tijd. Probeer het opnieuw.',

  'supportUkraine.banner.title': 'Steun Oekraïne',
  'supportUkraine.banner.body':
    'Tik om UNITED24 te openen en humanitaire hulp te steunen.',
};

