import { LANGUAGE_NAMES } from 'langs/languageNames';

export const ptBR: Record<string, string> = {
  'tabs.search': 'Buscar',
  'tabs.threads': 'Threads',
  'tabs.settings': 'Configurações',
  'nav.back': 'Voltar',
  'nav.thread': 'Thread',
  'nav.messages': 'Mensagens',
  'nav.threadsBack': 'Threads',
  'onboarding.slide0.title': 'Uma web sem ruído',
  'onboarding.slide0.body':
    'Conteúdo sem anúncios, rastreadores ou scripts desnecessários. Só texto e estrutura que são seus e funcionam rápido em qualquer dispositivo.',
  'onboarding.slide1.title': 'Navegue em threads',
  'onboarding.slide1.body':
    'Cada visita vira uma thread legível — uma sequência de páginas que você abriu. Como uma conversa com a web, onde o contexto é preservado e a navegação parece natural.',
  'onboarding.slide2.title': 'Sempre com você',
  'onboarding.slide2.body':
    'Os sites que você visita ficam salvos como threads no seu dispositivo, disponíveis offline com histórico completo — prontos para revisitar quando quiser.',
  'onboarding.back': 'Voltar',
  'onboarding.next': 'Próximo',
  'onboarding.getStarted': 'Começar',
  'onboarding.a11y.back': 'Voltar',
  'onboarding.a11y.next': 'Próximo',
  'onboarding.a11y.getStarted': 'Começar',
  'threads.header.addA11y': 'Adicionar',
  'threads.toast.saved.title': 'Salvo',
  'threads.toast.saved.message': 'Sua alteração foi registrada.',
  'threadList.empty': 'Ainda não há threads.',
  'messageList.empty': 'Nenhuma mensagem nesta thread.',
  'messageList.startPress': 'Iniciar',
  'messageForm.startPress': 'Iniciar',
  'search.title': 'Buscar',
  'search.subtitle': 'Busque diálogos, usuários ou qualquer outra coisa.',
  'settings.language': 'Idioma',
  'settings.account': 'Conta',
  'settings.languagePicker.title': 'Idioma',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Fechar',
  'a11y.dismiss': 'Dispensar',
  'accountSelector.title': 'Contas',
  'accountSelector.addNew': 'Adicionar nova conta',
  'accountSelector.empty': 'Ainda não há contas.',
  'accountForm.title': 'Nova conta',
  'accountForm.save': 'Salvar',
  'accountForm.nameLabel': 'Nome',
  'accountForm.namePlaceholder': 'Nome da conta',
  'accountForm.avatarHint': 'Deslize para escolher um emoji',
  'account.toast.savedTitle': 'Conta salva',
  'account.validation.nameRequired': 'O nome é obrigatório',
  'account.validation.nameTooLong': 'O nome é longo demais',
  'demo.thread.1.title': 'Sincronização de design',
  'demo.thread.1.desc': 'Discutir padrões de navegação para a v2.',
  'demo.thread.2.title': 'Release mobile',
  'demo.thread.3.title': 'Caixa de entrada do suporte',
  'demo.thread.3.desc': 'Chamados do fim de semana na fila.',
  'demo.thread.4.title': 'Thread simples A',
  'demo.thread.4.desc': 'Sem imagem, emoji ou cor do avatar — só iniciais.',
  'demo.thread.5.title': 'Notas do standup semanal',
  'demo.thread.5.desc': 'Título de duas palavras para iniciais.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Caso limite: título de uma letra.',
  'demo.thread.fallback.title': 'Thread',
  'demo.thread.fallback.desc': 'Cabeçalho de exemplo quando o id da thread é desconhecido.',
  'demo.message.1.label': 'Resuma esta thread',
  'demo.message.1.body':
    'Aqui vai um **resumo curto** da discussão:\n\n- Navegação\n- Listas\n- Estados vazios',
  'demo.message.2.input': 'Qual é a data de release?',
  'demo.message.3.label': 'Rascunho de resposta',
  'demo.message.3.body': 'Estamos mirando **na próxima sexta-feira** para o build mobile.',
  'demo.message.4.input': 'Executar verificação de conformidade',
  'demo.message.4.error': 'O serviço de conformidade expirou. Tente novamente.',

  'supportUkraine.banner.title': 'Apoie a Ucrânia',
  'supportUkraine.banner.body':
    'Toque para abrir o UNITED24 e apoiar o auxílio humanitário.',
};

