import { LANGUAGE_NAMES } from 'langs/languageNames';

export const ru: Record<string, string> = {
  'tabs.search': 'Поиск',
  'tabs.threads': 'Треды',
  'tabs.settings': 'Настройки',
  'nav.back': 'Назад',
  'nav.thread': 'Тред',
  'nav.messages': 'Сообщения',
  'nav.threadsBack': 'Треды',
  'onboarding.slide0.title': 'Веб без шума',
  'onboarding.slide0.body':
    'Контент без рекламы, трекеров и лишних скриптов. Только текст и структура, которые принадлежат вам и работают быстро на любом устройстве.',
  'onboarding.slide1.title': 'Просмотр в тредах',
  'onboarding.slide1.body':
    'Каждый визит становится читабельным тредом — последовательностью страниц, которые вы открывали. Как разговор с вебом: контекст сохраняется, а навигация ощущается естественно.',
  'onboarding.slide2.title': 'Всегда с вами',
  'onboarding.slide2.body':
    'Сайты, которые вы посещаете, сохраняются как треды на устройстве, доступны офлайн с полной историей — чтобы вернуться к ним в любой момент.',
  'onboarding.back': 'Назад',
  'onboarding.next': 'Далее',
  'onboarding.getStarted': 'Начать',
  'onboarding.a11y.back': 'Назад',
  'onboarding.a11y.next': 'Далее',
  'onboarding.a11y.getStarted': 'Начать',
  'threads.header.addA11y': 'Добавить',
  'threads.toast.saved.title': 'Сохранено',
  'threads.toast.saved.message': 'Изменение сохранено.',
  'threadList.empty': 'Тредов пока нет.',
  'messageList.empty': 'В этом треде нет сообщений.',
  'messageList.startPress': 'Начать',
  'messageForm.startPress': 'Начать',
  'messageForm.replyTextPlaceholder': 'Напишите ответ',
  'a11y.menu': 'Меню',
  'a11y.sendMessage': 'Отправить',
  'search.title': 'Поиск',
  'search.subtitle': 'Ищите диалоги, пользователей или что угодно.',
  'settings.language': 'Язык',
  'settings.account': 'Аккаунт',
  'settings.languagePicker.title': 'Язык',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Закрыть',
  'a11y.dismiss': 'Закрыть',
  'accountSelector.title': 'Аккаунты',
  'accountSelector.addNew': 'Добавить аккаунт',
  'accountSelector.empty': 'Аккаунтов пока нет.',
  'accountForm.title': 'Новый аккаунт',
  'accountForm.save': 'Сохранить',
  'accountForm.nameLabel': 'Имя',
  'accountForm.namePlaceholder': 'Имя аккаунта',
  'accountForm.avatarHint': 'Свайпните, чтобы выбрать эмодзи',
  'account.toast.savedTitle': 'Аккаунт сохранён',
  'account.validation.nameRequired': 'Имя обязательно',
  'account.validation.nameTooLong': 'Имя слишком длинное',
  'demo.thread.1.title': 'Синк по дизайну',
  'demo.thread.1.desc': 'Обсудить паттерны навигации для v2.',
  'demo.thread.2.title': 'Мобильный релиз',
  'demo.thread.3.title': 'Входящие поддержки',
  'demo.thread.3.desc': 'Тикеты с выходных в очереди.',
  'demo.thread.4.title': 'Простой тред A',
  'demo.thread.4.desc': 'Без картинки, эмодзи и оттенка аватара — только инициалы.',
  'demo.thread.5.title': 'Заметки еженедельного стендапа',
  'demo.thread.5.desc': 'Заголовок из двух слов для инициалов.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Пограничный случай: заголовок из одной буквы.',
  'demo.thread.fallback.title': 'Тред',
  'demo.thread.fallback.desc': 'Пример заголовка, когда id треда неизвестен.',
  'demo.message.1.label': 'Суммируй этот тред',
  'demo.message.1.body':
    'Вот **короткое резюме** обсуждения:\n\n- Навигация\n- Списки\n- Пустые состояния',
  'demo.message.2.input': 'Какая дата релиза?',
  'demo.message.3.label': 'Черновик ответа',
  'demo.message.3.body': 'Мы целимся в **следующую пятницу** для мобильной сборки.',
  'demo.message.4.input': 'Запустить проверку соответствия',
  'demo.message.4.error': 'Сервис соответствия не ответил вовремя. Попробуйте ещё раз.',

  'supportUkraine.banner.title': 'Поддержите Украину',
  'supportUkraine.banner.body': 'Нажмите, чтобы открыть UNITED24 и поддержать гуманитарную помощь.',
};

