import { LANGUAGE_NAMES } from 'langs/languageNames';

export const tr: Record<string, string> = {
  'tabs.search': 'Ara',
  'tabs.threads': 'Akışlar',
  'tabs.settings': 'Ayarlar',
  'nav.back': 'Geri',
  'nav.thread': 'Akış',
  'nav.messages': 'Mesajlar',
  'nav.threadsBack': 'Akışlar',
  'onboarding.slide0.title': 'Gürültüsüz bir web',
  'onboarding.slide0.body':
    'Reklamsız, izleyicisiz ve gereksiz betiksiz içerik. Sadece size ait metin ve yapı; her cihazda hızlı çalışır.',
  'onboarding.slide1.title': 'Akışlarda gezin',
  'onboarding.slide1.body':
    'Her ziyaret okunabilir bir akışa dönüşür — açtığınız sayfaların sırası. Web ile bir sohbet gibi: bağlam korunur ve gezinme doğal hissettirir.',
  'onboarding.slide2.title': 'Her zaman yanınızda',
  'onboarding.slide2.body':
    'Ziyaret ettiğiniz siteler cihazınızda akış olarak kaydedilir; çevrimdışı, tam gezinme geçmişiyle — istediğiniz an tekrar bakmaya hazır.',
  'onboarding.back': 'Geri',
  'onboarding.next': 'İleri',
  'onboarding.getStarted': 'Başla',
  'onboarding.a11y.back': 'Geri',
  'onboarding.a11y.next': 'İleri',
  'onboarding.a11y.getStarted': 'Başla',
  'threads.header.addA11y': 'Ekle',
  'threads.toast.saved.title': 'Kaydedildi',
  'threads.toast.saved.message': 'Değişikliğiniz kaydedildi.',
  'threadList.empty': 'Henüz akış yok.',
  'messageList.empty': 'Bu akışta mesaj yok.',
  'search.title': 'Ara',
  'search.subtitle': 'Diyalogları, kullanıcıları veya başka bir şeyi arayın.',
  'settings.language': 'Dil',
  'settings.account': 'Hesap',
  'settings.languagePicker.title': 'Dil',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Kapat',
  'a11y.dismiss': 'Kapat',
  'accountSelector.title': 'Hesaplar',
  'accountSelector.addNew': 'Yeni hesap ekle',
  'accountSelector.empty': 'Henüz hesap yok.',
  'accountForm.title': 'Yeni hesap',
  'accountForm.save': 'Kaydet',
  'accountForm.nameLabel': 'Ad',
  'accountForm.namePlaceholder': 'Hesap adı',
  'accountForm.avatarHint': 'Emoji seçmek için kaydırın',
  'account.toast.savedTitle': 'Hesap kaydedildi',
  'account.validation.nameRequired': 'Ad gerekli',
  'account.validation.nameTooLong': 'Ad çok uzun',
  'demo.thread.1.title': 'Tasarım senkronu',
  'demo.thread.1.desc': 'v2 için gezinme desenlerini tartışın.',
  'demo.thread.2.title': 'Mobil sürüm',
  'demo.thread.3.title': 'Destek gelen kutusu',
  'demo.thread.3.desc': 'Hafta sonundan kalan talepler kuyruğa alındı.',
  'demo.thread.4.title': 'Basit akış A',
  'demo.thread.4.desc': 'Görsel, emoji veya avatar tonu yok — sadece baş harfler.',
  'demo.thread.5.title': 'Haftalık standup notları',
  'demo.thread.5.desc': 'Baş harfler için iki kelimelik başlık.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Kenar durum: tek harfli başlık.',
  'demo.thread.fallback.title': 'Akış',
  'demo.thread.fallback.desc': 'Akış kimliği bilinmediğinde örnek başlık.',
  'demo.message.1.label': 'Bu akışı özetle',
  'demo.message.1.body':
    'İşte tartışmanın **kısa bir özeti**:\n\n- Gezinme\n- Listeler\n- Boş durumlar',
  'demo.message.2.input': 'Yayın tarihi nedir?',
  'demo.message.3.label': 'Yanıt taslağı',
  'demo.message.3.body': 'Mobil derleme için hedefimiz **gelecek Cuma**.',
  'demo.message.4.input': 'Uyumluluk kontrolünü çalıştır',
  'demo.message.4.error': 'Uyumluluk hizmeti zaman aşımına uğradı. Lütfen tekrar deneyin.',
};

