import { LANGUAGE_NAMES } from 'langs/languageNames';

export const uk: Record<string, string> = {
  'tabs.search': 'Пошук',
  'tabs.threads': 'Треди',
  'tabs.settings': 'Налаштування',
  'nav.back': 'Назад',
  'nav.thread': 'Тред',
  'nav.messages': 'Повідомлення',
  'nav.threadsBack': 'Треди',
  'onboarding.slide0.title': 'Простий веб без шуму',
  'onboarding.slide0.body':
    'Контент без реклами, трекерів і зайвих скриптів. Лише текст і структура, які належать вам і працюють швидко на будь-якому пристрої.',
  'onboarding.slide1.title': 'Перегляд у тредах',
  'onboarding.slide1.body':
    'Кожен візит стає зручним для читання тредом — послідовністю сторінок, які ви відкривали. Як розмова з вебом: контекст зберігається, а навігація відчувається природно.',
  'onboarding.slide2.title': 'Завжди з вами',
  'onboarding.slide2.body':
    'Сайти, які ви відвідуєте, зберігаються як треди на пристрої — доступні офлайн із повною історією перегляду, щоб повернутися до них будь-коли.',
  'onboarding.back': 'Назад',
  'onboarding.next': 'Далі',
  'onboarding.getStarted': 'Почати',
  'onboarding.a11y.back': 'Назад',
  'onboarding.a11y.next': 'Далі',
  'onboarding.a11y.getStarted': 'Почати',
  'threads.header.addA11y': 'Додати',
  'threads.toast.saved.title': 'Збережено',
  'threads.toast.saved.message': 'Вашу зміну записано.',
  'threadList.empty': 'Поки що немає тредів.',
  'messageList.empty': 'У цьому треді немає повідомлень.',
  'search.title': 'Пошук',
  'search.subtitle': 'Шукайте діалоги, користувачів або будь-що інше.',
  'settings.language': 'Мова',
  'settings.account': 'Обліковий запис',
  'settings.languagePicker.title': 'Мова',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Закрити',
  'a11y.dismiss': 'Закрити',
  'accountSelector.title': 'Облікові записи',
  'accountSelector.addNew': 'Додати обліковий запис',
  'accountSelector.empty': 'Поки що немає облікових записів.',
  'accountForm.title': 'Новий обліковий запис',
  'accountForm.save': 'Зберегти',
  'accountForm.nameLabel': 'Ім’я',
  'accountForm.namePlaceholder': 'Назва облікового запису',
  'accountForm.avatarHint': 'Проведіть, щоб обрати емодзі',
  'account.toast.savedTitle': 'Обліковий запис збережено',
  'account.validation.nameRequired': "Ім'я обов'язкове",
  'account.validation.nameTooLong': "Ім'я задовге",
  'demo.thread.1.title': 'Дизайн-синк',
  'demo.thread.1.desc': 'Обговорюємо патерни навігації для v2.',
  'demo.thread.2.title': 'Мобільний реліз',
  'demo.thread.3.title': 'Підтримка — вхідні',
  'demo.thread.3.desc': 'Квитки з вихідних у черзі.',
  'demo.thread.4.title': 'Тред Plain A',
  'demo.thread.4.desc': 'Без зображення, емодзі чи відтінку аватара — лише ініціали.',
  'demo.thread.5.title': 'Нотатки щотижневого стендапу',
  'demo.thread.5.desc': 'Заголовок із двох слів для ініціалів.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Крайній випадок: заголовок з однієї літери.',
  'demo.thread.fallback.title': 'Тред',
  'demo.thread.fallback.desc': 'Приклад заголовка, коли id треду невідомий.',
  'demo.message.1.label': 'Підсумуй цей тред',
  'demo.message.1.body':
    'Ось **короткий підсумок** обговорення:\n\n- Навігація\n- Списки\n- Порожні стани',
  'demo.message.2.input': 'Яка дата релізу?',
  'demo.message.3.label': 'Чернетка відповіді',
  'demo.message.3.body': 'Орієнтуємося на **наступну п’ятницю** для мобільної збірки.',
  'demo.message.4.input': 'Запусти перевірку відповідності',
  'demo.message.4.error': 'Служба перевірки не відповіла вчасно. Спробуйте ще раз.',
};

