import { LANGUAGE_NAMES } from 'langs/languageNames';

export const uz: Record<string, string> = {
  'tabs.search': 'Qidirish',
  'tabs.threads': 'Mavzular',
  'tabs.settings': 'Sozlamalar',
  'nav.back': 'Orqaga',
  'nav.thread': 'Mavzu',
  'nav.messages': 'Xabarlar',
  'nav.threadsBack': 'Mavzular',
  'onboarding.slide0.title': 'Shovqinsiz veb',
  'onboarding.slide0.body':
    'Reklamasiz, kuzatuvchisiz va keraksiz skriptlarsiz kontent. Faqat sizga tegishli matn va tuzilma — har qanday qurilmada tez ishlaydi.',
  'onboarding.slide1.title': 'Mavzularda ko‘ring',
  'onboarding.slide1.body':
    'Har bir tashrif o‘qilishi oson mavzuga aylanadi — ochgan sahifalaringiz ketma-ketligi. Veb bilan suhbat kabi: kontekst saqlanadi va navigatsiya tabiiy tuyuladi.',
  'onboarding.slide2.title': 'Doimo yoningizda',
  'onboarding.slide2.body':
    'Tashrif buyurgan saytlariңiz qurilmangizda mavzu sifatida saqlanadi, oflayn ham to‘liq tarix bilan — istalgan payt qaytishga tayyor.',
  'onboarding.back': 'Orqaga',
  'onboarding.next': 'Keyingi',
  'onboarding.getStarted': 'Boshlash',
  'onboarding.a11y.back': 'Orqaga',
  'onboarding.a11y.next': 'Keyingi',
  'onboarding.a11y.getStarted': 'Boshlash',
  'threads.header.addA11y': 'Qo‘shish',
  'threads.toast.saved.title': 'Saqlangan',
  'threads.toast.saved.message': "O'zgarish saqlandi.",
  'threadList.empty': 'Hali mavzular yo‘q.',
  'messageList.empty': 'Bu mavzuda xabarlar yo‘q.',
  'messageList.startPress': 'Boshlash',
  'messageForm.startPress': 'Boshlash',
  'messageForm.replyTextPlaceholder': 'Javob yozing',
  'a11y.menu': 'Menyu',
  'a11y.sendMessage': 'Yuborish',
  'search.title': 'Qidirish',
  'search.subtitle': 'Dialoglar, foydalanuvchilar yoki boshqa narsani qidiring.',
  'settings.language': 'Til',
  'settings.account': 'Hisob',
  'settings.languagePicker.title': 'Til',
  'language.name.en': LANGUAGE_NAMES.en,
  'language.name.de': LANGUAGE_NAMES.de,
  'language.name.es': LANGUAGE_NAMES.es,
  'language.name.fr': LANGUAGE_NAMES.fr,
  'language.name.it': LANGUAGE_NAMES.it,
  'language.name.uk': LANGUAGE_NAMES.uk,
  'language.name.nl': LANGUAGE_NAMES.nl,
  'language.name.pt-BR': LANGUAGE_NAMES['pt-BR'],
  'language.name.ar': LANGUAGE_NAMES.ar,
  'language.name.tr': LANGUAGE_NAMES.tr,
  'language.name.uz': LANGUAGE_NAMES.uz,
  'language.name.kk': LANGUAGE_NAMES.kk,
  'language.name.ru': LANGUAGE_NAMES.ru,
  'language.name.fa': LANGUAGE_NAMES.fa,
  'a11y.close': 'Yopish',
  'a11y.dismiss': 'Bekor qilish',
  'accountSelector.title': 'Hisoblar',
  'accountSelector.addNew': 'Yangi hisob qo‘shish',
  'accountSelector.empty': 'Hali hisoblar yo‘q.',
  'accountForm.title': 'Yangi hisob',
  'accountForm.save': 'Saqlash',
  'accountForm.nameLabel': 'Nomi',
  'accountForm.namePlaceholder': 'Hisob nomi',
  'accountForm.avatarHint': 'Emoji tanlash uchun suring',
  'account.toast.savedTitle': 'Hisob saqlandi',
  'account.validation.nameRequired': 'Nomi majburiy',
  'account.validation.nameTooLong': 'Nomi juda uzun',
  'demo.thread.1.title': 'Dizayn sinxroni',
  'demo.thread.1.desc': 'v2 uchun navigatsiya uslublarini muhokama qiling.',
  'demo.thread.2.title': 'Mobil reliz',
  'demo.thread.3.title': 'Qo‘llab-quvvatlash kiruvchi',
  'demo.thread.3.desc': 'Dam olish kunlaridan qolgan murojaatlar navbatda.',
  'demo.thread.4.title': 'Oddiy mavzu A',
  'demo.thread.4.desc': 'Rasm, emoji yoki avatar rangi yo‘q — faqat bosh harflar.',
  'demo.thread.5.title': 'Haftalik standap qaydlari',
  'demo.thread.5.desc': 'Bosh harflar uchun ikki so‘zli sarlavha.',
  'demo.thread.6.title': 'X',
  'demo.thread.6.desc': 'Chegara holat: bitta harfli sarlavha.',
  'demo.thread.fallback.title': 'Mavzu',
  'demo.thread.fallback.desc': "Mavzu id noma'lum bo‘lsa, namuna sarlavha.",
  'demo.message.1.label': 'Bu mavzuni qisqacha bayon qiling',
  'demo.message.1.body':
    'Muhokamaning **qisqa xulosasi**:\n\n- Navigatsiya\n- Ro‘yxatlar\n- Bo‘sh holatlar',
  'demo.message.2.input': 'Reliz sanasi qachon?',
  'demo.message.3.label': 'Javob qoralamasi',
  'demo.message.3.body': 'Mobil build uchun **kelasi juma**ni mo‘ljallayapmiz.',
  'demo.message.4.input': 'Muvofiqlik tekshiruvini ishga tushirish',
  'demo.message.4.error': 'Muvofiqlik xizmati vaqtida javob bermadi. Qayta urinib ko‘ring.',

  'supportUkraine.banner.title': 'Ukrainani qo‘llab-quvvatlang',
  'supportUkraine.banner.body':
    'UNITED24 saytiga o‘tish va gumanitar yordamni qo‘llab-quvvatlash uchun bosing.',
};

